[workspace]
resolver = "2"
members = [
    "ff_standard_lib",
    "ff_data_server",
    "ff_data_server",
    "example_test_strategy",
    "ff_strategy_registry",
    "test_data_parser",
    "ff_tests/ledger_test",
    "ff_tests/rithmic_test_quote_strategy", "ff_tests/rithmic_order_test",
]



