user = "Kevinjamesmonaghan@outlook.com"
system_name = ""
password = "cDbJbQLV"
app_name = "fund-forge"
app_version = "1.0"
aggregated_quotes = false
template_version = "5.27"
pem = "ff_standard_lib/src/apis/rithmic/rithmic_ssl_cert_auth_params.pem"
base_url = "wss://rituz00100.rithmic.com:443"
broker = "Test"