[package]
name = "test_data_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
ff_standard_lib = { path = "../ff_standard_lib", features = ["server"]}
chrono = "0.4.38"
rust_decimal = "*"
rust_decimal_macros ="1.36.0"
tokio = "1.40.0"